export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_REMOVE_ITEMS = "CART_REMOVE_ITEMS";

export const CART_DETAILS_REQUEST = "CART_DETAILS_REQUEST";
export const CART_DETAILS_SUCCESS = "CART_DETAILS_SUCCESS";
export const CART_DETAILS_FAIL = "CART_DETAILS_FAIL";
export const CART_DETAILS_RESET = "CART_DETAILS_RESET";

export const CART_UPDATE_REQUEST = "CART_UPDATE_REQUEST";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";
export const CART_UPDATE_FAIL = "CART_UPDATE_FAIL";
export const CART_UPDATE_RESET = "CART_UPDATE_RESET";

export const CART_DETAIL_ADD_ITEM = "CART_DETAIL_ADD_ITEM";
export const CART_DETAIL_REMOVE_ITEM = "CART_DETAIL_REMOVE_ITEM";
export const CART_DETAIL_REMOVE_ITEMS = "CART_DETAIL_REMOVE_ITEMS";
